config/routes.rb
Rails.application.routes.draw do
  resources :home
  get 'team', to: 'team#team'
  get 'contact', to: 'contact#contact'
  get 'welcome/:first_name', to:'welcome#index'
  get '/show/:id', to: 'home#show'
 
  
  root 'home#index'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User" 
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  has_many :gossips
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossip = Gossip.all
  end

def show
  @gossip = Gossip.find(params[:id])
end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def team
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @first_name = params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/contact.html.erb
<h1>Contact</h1>

app/views/home/index.html.erb
<h1>Bienvenue sur The Gossip Project</h1>

<h2>Welcome!</h2>

  <h2> Voici les gossips:</h2>
        <% @gossip.each do |gossip| %>
  <table class="table">
    <td class="text-left"><%=  gossip.user.first_name %></td>
    <td class="text-right"><%= link_to "#{gossip.title}", "/home/#{gossip.id}"%>
    </table>
<% end %>

app/views/home/show.html.erb
<h1 class = text-center> Voici le Gossip n <%= @gossip.id%></h1>
<div class=container><%= @gossip.title%> </div>
<div class = container><%= @gossip.content%> </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "The Gossip Project", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "L'équipe", team_path, class:"navbar-brand" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contacts", contact_path, class:"navbar-brand" %>
      </li>
      <%#<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>%>
      </li>
    </ul>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/team/team.html.erb
<h1>Team</h1>

app/views/welcome/index.html.erb
<h1>Welcome <%= @first_name .capitalize%> !</h1>
<p>text here</p>